apiVersion: v2
appVersion: '1.0'
description: A Helm chart for nfdiv-manage-case-e2e-tests repo
name: nfdiv-manage-case-e2e-tests
home: https://github.com/hmcts/nfdiv-manage-case-e2e-tests
version: 0.0.108
dependencies:
  - name: nodejs
    version: 3.2.0
    repository: 'oci://hmctspublic.azurecr.io/helm'
  - name: idam-pr
    version: 2.3.0
    repository: 'oci://hmctspublic.azurecr.io/helm'
    condition: idam-pr.enabled
