export enum CommonContent {
  pageTitle = "Apply: divorce or dissolution",
  createCase = "Create Case",
  continueButton = "Continue",
  findAddressButton = "Find address",
  saveApplication = "Save Application",
  jurisdictionOption = "Family Divorce",
  caseTypeOption = "New Law Case",
  button = "Start",
  addNewButton = "Add new",
  continue = "Continue",
  Yes = "Yes",
  submitApplication = "Submit Application",
  fee = "£612",
}
