export enum CommonContent {
  pageTitle = "Apply: divorce or dissolution",
  createCase = "Create Case",
  addNewButton = "Add new",
  continueButton = "Continue",
  removeButton = "Remove",
  submitButton = "Submit",
  findAddressButton = "Find address",
  saveApplication = "Save Application",
  saveAndContinue = "Save and continue",
  jurisdictionOption = "Family Divorce",
  caseTypeOption = "New Law Case",
  button = "Start",
  continue = "Continue",
  Yes = "Yes",
  submitApplication = "Submit Application",
  fee = "£612",
  applicantOrApplicantSolicitorOption = "Applicant / Applicant's Solicitor",
  correspondenceTab = "Correspondence",
}
